// These are used because the Datamuse API requires a noun to return associated adjectives. So I have used this list of
// nouns that express traits from the Emotional Competency website: http://www.emotionalcompetency.com/nouns.htm

export const seedList = ['actor', 'addict', 'adulterer', 'adventurer', 'aggressor', 'agitator', 'alcoholic', 'amateur',
  'anarchist', 'angel', 'animal', 'antagonist', 'arch+villain', 'artist', 'atheist', 'authority', 'babe', 'baby',
  'backseat+driver', 'bastard', 'beauty', 'beginner', 'believer', 'bigot', 'bigshot', 'bimbo', 'blabbermouth',
  'black+sheep', 'blockhead', 'boaster', 'bohemian', 'bonehead', 'boob', 'bookworm', 'bore', 'born+fighter', 'boss',
  'braggart', 'brain', 'brat', 'brown+nose', 'brute', 'buddy', 'buffoon', 'bully', 'bum', 'busybody', 'butterfingers',
  'capitalist', 'careerist', 'celibate', 'chameleon', 'champion', 'character', 'charmer', 'chatterbox', 'chatterer',
  'chauvinist', 'cheapskate', 'cheater', 'chicken', 'child', 'christian', 'city+slicker', 'clown', 'comedian',
  'comforter', 'comic', 'communist', 'complainer', 'compulsive', 'conformist', 'connoisseur', 'conservationist',
  'conservative', 'copycat', 'cow', 'coward', 'crab', 'creep', 'critic', 'crook', 'cry+baby', 'culprit', 'cutie',
  'cynic', 'daredevil', 'darling', 'daydreamer', 'deadbeat', 'deceiver', 'degenerate', 'delinquent', 'democrat',
  'deviate', 'devil', 'devils+advocate', 'diehard', 'dingbat', 'diplomat', 'disciplinarian', 'dog', 'doll',
  'do+nothing', 'dope', 'dreamer', 'drifter', 'drudge', 'drunk', 'drunkard', 'dude', 'dumbbell', 'dummy', 'dunce',
  'early+bird', 'eavesdropper', 'eccentric', 'egghead', 'enthusiast', 'expert', 'extremist', 'extrovert', 'failure',
  'fake', 'faker', 'false+friend', 'fanatic', 'fashion—plate', 'feminist', 'fighter', 'flirt', 'follower', 'fool',
  'fox', 'freak', 'friend', 'fruit', 'gambler', 'gangster', 'geek', 'geezer', 'genius', 'gentleman', 'giant', 'glutton',
  'go+getter', 'gold+digger', 'good+samaritan', 'goody+goody', 'goof', 'gossip', 'gourmet', 'granny', 'grouch',
  'grumbler', 'grump', 'ham', 'hanger+on', 'hardhead', 'hard nose', 'heartbreaker', 'heathen', 'heavyweight', 'hermit',
  'hero', 'hick', 'high+flier', 'hippie', 'homebody', 'homemaker', 'honey', 'hoodlum', 'hopeful', 'hotshot',
  'humanitarian', 'hunk', 'hypocrite', 'idealist', 'idiot', 'imbecile', 'incompetent', 'individual', 'individualist',
  'inferior', 'innocent', 'innovator', 'intellectual', 'introvert', 'invalid', 'jackass', 'jerk', 'jester', 'jock',
  'joker', 'junkie', 'klutz', 'knockout', 'know+it+all', 'knucklehead', 'ladies+man', 'lady+bountiful', 'lady+killer',
  'lawbreaker', 'lazybones', 'leader', 'lecher', 'left+winger', 'lefty', 'liar', 'liberal', 'life+of+the+party',
  'lightweight', 'loafer', 'loner', 'longhair', 'loony', 'loser', 'loudmouth', 'love', 'lunatic', 'lush', 'machine',
  'madman', 'maniac', 'master', 'mastermind', 'matchmaker', 'materialist', 'menace', 'merrymaker', 'militant', 'misfit',
  'moderate', 'money+grubber', 'monster', 'moocher', 'moron', 'mortal', 'mouth', 'nag', 'neurotic', 'night+owl',
  'nobody', 'noise+maker', 'nonconformist', 'novice', 'nuisance', 'nut', 'obsessive', 'obstructionist', 'opportunist',
  'oppositionalist', 'optimist', 'organizer', 'outcast', 'outsider', 'pacifist', 'packrat', 'pain+in+the+neck', 'pal',
  'paranoid', 'party+girl', 'party+pooper', 'patriot', 'peacemaker', 'perfectionist', 'pervert', 'pessimist', 'pest',
  'philosopher', 'phony', 'pig', 'pioneer', 'playboy', 'player', 'playmate', 'plaything', 'pleasure+seeker', 'plodder',
  'poet', 'pothead', 'practical+joker', 'pragmatist', 'predator', 'prima donna', 'pro', 'professional', 'profiteer',
  'protagonist', 'protector', 'psychic', 'psychopath', 'psychotic', 'punk', 'pushover', 'quack', 'quick+thinker',
  'quitter', 'racist', 'radical', 'rat', 'realist', 'rebel', 'recluse', 'redneck', 'republican', 'right+winger',
  'ringleader', 'riot', 'romantic', 'romeo', 'rowdy', 'runt', 'saint', 'samaritan', 'savage', 'savior', 'scapegoat',
  'scaredy+cat', 'scatterbrain', 'scoundrel', 'screwball', 'scrooge', 'scum', 'sensationalist', 'sentimentalist',
  'sexist', 'sex+maniac', 'sex+object', 'sexpot', 'showman', 'show+off', 'shrimp', 'sinner', 'sissy', 'sitting+duck',
  'skeptic', 'slacker', 'slave driver', 'sleepyhead', 'slob', 'slouch', 'slowpoke', 'slug', 'slut', 'smart+aleck',
  'smarty', 'snake', 'sneak', 'snob', 'snoop', 'snot', 'so+and+so', 'softy', 'somebody', 'speculator', 'spoilsport',
  'sport', 'sportsman', 'sportswoman', 'square', 'star', 'stereotype', 'stick+in+the+mud', 'stickler', 'stinker',
  'stoic', 'storyteller', 'strategist', 'stud', 'stuffed+shirt', 'success', 'sucker', 'sweetheart', 'sweetie',
  'sympathizer', 'talker', 'tattler', 'tattletale', 'tease', 'teaser', 'teenybopper', 'tenor', 'thief', 'thinker',
  'tightwad', 'tomboy', 'tormentor', 'tough', 'traditionalist', 'traitor', 'tramp', 'trash', 'traveler', 'troublemaker',
  'true+believer', 'turkey', 'twerp', 'twit', 'two+timer', 'ultraconservative', 'unfortunate', 'user', 'vandal',
  'vegetable', 'vegetarian', 'victim', 'victor', 'virgin', 'weakling', 'weasel', 'weirdo', 'whiner', 'whizkid', 'wimp',
  'winner', 'wino', 'wise+guy', 'witch', 'womanizer', 'worker', 'workhorse', 'world+traveler', 'worm', 'worrywart',
  'wreck'];
