export const seedList = ['actor', 'addict', 'adulterer', 'adventurer', 'aggressor', 'agitator', 'alcoholic', 'amateur',
  'anarchist', 'angel', 'animal', 'antagonist', 'arch+villain', 'artist', 'atheist', 'authority', 'babe', 'baby',
  'backseat+driver', 'bastard', 'beauty', 'beginner', 'believer', 'bigot', 'bigshot', 'bimbo', 'blabbermouth',
  'black+sheep', 'blockhead', 'boaster', 'bohemian', 'bonehead', 'boob', 'bookworm', 'bore', 'born+fighter', 'boss',
  'braggart', 'brain', 'brat', 'brown+nose', 'brute', 'buddy', 'buffoon', 'bully', 'bum', 'busybody', 'butterfingers',
  'capitalist', 'careerist', 'celibate', 'chameleon', 'champion', 'character', 'charmer', 'chatterbox', 'chatterer',
  'chauvinist', 'cheapskate', 'cheater', 'chicken', 'child', 'christian', 'city+slicker', 'clown', 'comedian',
  'comforter', 'comic', 'communist', 'complainer', 'compulsive', 'conformist', 'connoisseur', 'conservationist',
  'conservative', 'copycat', 'cow', 'coward', 'crab', 'creep', 'critic', 'crook', 'cry+baby', 'culprit', 'cutie',
  'cynic', 'daredevil', 'darling', 'daydreamer', 'deadbeat', 'deceiver', 'degenerate', 'delinquent', 'democrat',
  'deviate', 'devil', 'devils+advocate', 'diehard', 'dingbat', 'diplomat', 'disciplinarian', 'dog', 'doll',
  'do+nothing', 'dope', 'dreamer', 'drifter', 'drudge', 'drunk', 'drunkard', 'dude', 'dumbbell', 'dummy', 'dunce',
  'early+bird', 'eavesdropper', 'eccentric', 'egghead', 'enthusiast', 'expert', 'extremist', 'extrovert', 'failure',
  'fake', 'faker', 'false+friend', 'fanatic', 'fashion—plate', 'feminist', 'fighter', 'flirt', 'follower', 'fool',
  'fox', 'freak', 'friend', 'fruit', 'gambler', 'gangster', 'geek', 'geezer', 'genius', 'gentleman', 'giant', 'glutton',
  'go+getter', 'gold+digger', 'good+samaritan', 'goody+goody', 'goof', 'gossip', 'gourmet', 'granny', 'grouch',
  'grumbler', 'grump', 'ham', 'hanger+on', 'hardhead', 'hard nose', 'heartbreaker', 'heathen', 'heavyweight', 'hermit',
  'hero', 'hick', 'high+flier', 'hippie', 'homebody', 'homemaker', 'honey', 'hoodlum', 'hopeful', 'hotshot',
  'humanitarian', 'hunk', 'hypocrite', 'idealist', 'idiot', 'imbecile', 'incompetent', 'individual', 'individualist',
  'inferior', 'innocent', 'innovator', 'intellectual', 'introvert', 'invalid', 'jackass', 'jerk', 'jester', 'jock',
  'joker', 'junkie', 'klutz', 'knockout', 'know+it+all', 'knucklehead', 'ladies+man', 'lady+bountiful', 'lady+killer',
  'lawbreaker', 'lazybones', 'leader', 'lecher', 'left+winger', 'lefty', 'liar', 'liberal', 'life+of+the+party',
  'lightweight', 'loafer', 'loner', 'longhair', 'loony', 'loser', 'loudmouth', 'love', 'lunatic', 'lush', 'machine',
  'madman', 'maniac', 'master', 'mastermind', 'matchmaker', 'materialist', 'menace', 'merrymaker', 'militant', 'misfit',
  'moderate', 'money+grubber', 'monster', 'moocher', 'moron', 'mortal', 'mouth', 'nag', 'neurotic', 'night+owl',
  'nobody', 'noise+maker', 'nonconformist', 'novice', 'nuisance', 'nut', 'obsessive', 'obstructionist', 'opportunist',
  'oppositionalist', 'optimist', 'organizer', 'outcast', 'outsider', 'pacifist', 'packrat', 'pain+in+the+neck', 'pal',
  'paranoid', 'party+girl', 'party+pooper', 'patriot', 'peacemaker', 'perfectionist', 'pervert', 'pessimist', 'pest',
  'philosopher', 'phony', 'pig', 'pioneer', 'playboy', 'player', 'playmate', 'plaything', 'pleasure+seeker', 'plodder',
  'poet', 'pothead', 'practical+joker', 'pragmatist', 'predator', 'prima donna', 'pro', 'professional', 'profiteer',
  'protagonist', 'protector', 'psychic', 'psychopath', 'psychotic', 'punk', 'pushover', 'quack', 'quick+thinker',
  'quitter', 'racist', 'radical', 'rat', 'realist', 'rebel', 'recluse', 'redneck', 'republican', 'right+winger',
  'ringleader', 'riot', 'romantic', 'romeo', 'rowdy', 'runt', 'saint', 'samaritan', 'savage', 'savior', 'scapegoat',
  'scaredy+cat', 'scatterbrain', 'scoundrel', 'screwball', 'scrooge', 'scum', 'sensationalist', 'sentimentalist',
  'sexist', 'sex+maniac', 'sex+object', 'sexpot', 'showman', 'show+off', 'shrimp', 'sinner', 'sissy', 'sitting+duck',
  'skeptic', 'slacker', 'slave driver', 'sleepyhead', 'slob', 'slouch', 'slowpoke', 'slug', 'slut', 'smart+aleck',
  'smarty', 'snake', 'sneak', 'snob', 'snoop', 'snot', 'so+and+so', 'softy', 'somebody', 'speculator', 'spoilsport',
  'sport', 'sportsman', 'sportswoman', 'square', 'star', 'stereotype', 'stick+in+the+mud', 'stickler', 'stinker',
  'stoic', 'storyteller', 'strategist', 'stud', 'stuffed+shirt', 'success', 'sucker', 'sweetheart', 'sweetie',
  'sympathizer', 'talker', 'tattler', 'tattletale', 'tease', 'teaser', 'teenybopper', 'tenor', 'thief', 'thinker',
  'tightwad', 'tomboy', 'tormentor', 'tough', 'traditionalist', 'traitor', 'tramp', 'trash', 'traveler', 'troublemaker',
  'true+believer', 'turkey', 'twerp', 'twit', 'two+timer', 'ultraconservative', 'unfortunate', 'user', 'vandal',
  'vegetable', 'vegetarian', 'victim', 'victor', 'virgin', 'weakling', 'weasel', 'weirdo', 'whiner', 'whizkid', 'wimp',
  'winner', 'wino', 'wise+guy', 'witch', 'womanizer', 'worker', 'workhorse', 'world+traveler', 'worm', 'worrywart',
  'wreck'];



// export const seedList = [
//   'academician', 'acceptor', 'ace', 'ace+in+the+hole', 'achiever', 'adept', 'adherent', 'administrator', 'admirer',
//   'adorer', 'advantage', 'adviser', 'advisor', 'advocate', 'aelurophile', 'aerophile', 'aesthete', 'aficionada',
//   'aficionado', 'aid', 'aide', 'ailurophile', 'alannah', 'alleviator', 'ally', 'almsgiver', 'almsperson', 'alternate',
//   'altruist', 'agent', 'workaholic', 'ambassador', 'amoret', 'angel', 'aficionada', 'aficionado', 'affluential',
//   'americophile', 'amerindophile', 'amerindophilist', 'anglophile', 'apostle', 'appreciator', 'apprentice',
//   'arctophile', 'arbiter', 'archetype', 'architect', 'artisan', 'artist', 'artiste', 'ascendant', 'aspirant', 'asset',
//   'assignee', 'assigner', 'assistant', 'associate', 'astrophile', 'athlete', 'attendant', 'audiophile', 'author',
//   'authority', 'autodidact', 'awardee', 'baby', 'backbone', 'backer', 'backup', 'ball+of+fire', 'baron', 'beata',
//   'beatus', 'beaut', 'beauty', 'beau+ideal', 'bees+knees', 'begetter', 'being', 'bel+esprit', 'believer', 'belle',
//   'benchmark', 'benefactor', 'benefactress', 'beneficiary', 'benefit', 'bestower', 'bibliophile', 'big+cheese',
//   'big+enchilada', 'big+fish', 'big+gun', 'big+wheel', 'bigwig', 'biophile', 'blessing', 'bodyguard', 'bon+vivant',
//   'boss', 'booster', 'brain', 'brass', 'brother', 'bud', 'buddy', 'buff', 'bundle+of+energy', 'bundle+of+joy',
//   'builder', 'campaigner', 'captain', 'carer', 'caretaker', 'cartophile', 'catalyst', 'cats+meow', 'cause', 'cavalier',
//   'celebrant', 'celebrator', 'center+of+attention', 'ceo', 'cfo', 'chair', 'chairperson', 'chamberlain', 'champ',
//   'champion', 'chaperon', 'charmer', 'cherub', 'cherisher', 'chief', 'chieftan', 'child', 'chum', 'cinephile',
//   'clerisy', 'climber', 'coadjutant', 'coadjutor', 'cognoscente', 'cognoscenti', 'cohort', 'coiner', 'collaborator',
//   'colleague', 'collector', 'comforter', 'commander', 'companion', 'compeller', 'complement', 'composer', 'comrade',
//   'concert+pianist', 'concierge', 'conductor', 'confederate', 'conferrer', 'confidant', 'confrere', 'connoisseur',
//   'conservator', 'consoler', 'consul', 'consultant', 'contributor', 'controller', 'convive', 'cooperator', 'corker',
//   'cornerstone', 'cosmocrat', 'cosmopolitan', 'cosmopolite', 'councillor', 'counsel', 'counselor', 'counsellor',
//   'count', 'co+worker', 'crackerjack', 'craftsperson', 'creator', 'credit', 'crew', 'cub', 'curator', 'custodian',
//   'cynosure', 'dad', 'dancer', 'darling', 'daughter', 'dean', 'dear', 'defender', 'deipnosophist', 'demophile',
//   'designer', 'devisee', 'devisor', 'devotee', 'digerati', 'dilly', 'director', 'disciple', 'discophile', 'discoverer',
//   'distributor', 'doer', 'doll', 'donee', 'donor', 'doter', 'doozy', 'doula', 'doyen', 'doyenne', 'dream', 'dreamboat',
//   'duke', 'dynamo', 'eager+beaver', 'earl', 'ecstatic', 'einstein', 'elder', 'employer', 'enchanter', 'enchantress',
//   'encourager', 'endorser', 'engineer', 'enkindler', 'enophile', 'ensurer', 'entertainer', 'enthusiast', 'entrepreneur',
//   'epididact', 'epicure', 'epicurean', 'epitome', 'ergophile', 'escort', 'essence', 'eudaimonist', 'example', 'exec',
//   'executive', 'exemplar', 'excellency', 'experimenter', 'expert', 'exponent', 'facilitator', 'family', 'fan',
//   'fancier', 'fascinator', 'fashioner', 'favourite', 'fellow+worker', 'fiance', 'financier', 'fireball', 'fireman',
//   'first+in+command', 'flame', 'folks', 'foodie', 'foodophile', 'force', 'forebearer', 'forefather', 'foreman',
//   'forerunner', 'foreseer', 'foundation', 'founder', 'fount', 'fountain', 'fountainhead', 'francophile', 'friend',
//   'gallophile', 'gastronome', 'gastronomer', 'gastronomist', 'generator', 'gem', 'genius', 'gentleman', 'gentlewoman',
//   'germanophile', 'gift', 'givee', 'giver', 'godparent', 'godsend', 'go+getter', 'good+egg', 'good+samaritan',
//   'good+spirit', 'good+thing', 'gourmet', 'governor', 'grandee', 'grantee', 'grantor', 'grubstaker', 'guarantor',
//   'guardian', 'guest', 'guidance+counsellor', 'guide', 'guru', 'handler', 'hard+worker', 'head', 'head+honcho',
//   'head+person', 'heart', 'heartthrob', 'heavy+hitter', 'heavyweight', 'height', 'heir', 'heiress', 'heliophile',
//   'hellenophile', 'help', 'helper', 'helpmate', 'heritor', 'heritress', 'heritrix', 'hero', 'heroine', 'highflier',
//   'high+flier', 'hippophile', 'hit', 'homemaker', 'hopeful', 'host', 'hotshot', 'hot+stuff', 'house+sitter',
//   'human+being', 'humanitarian', 'humdinger', 'husband', 'icon', 'iconophile', 'ideal', 'idol', 'idolizer',
//   'illuminator', 'improvement', 'inamorata', 'inamorato', 'individual', 'indophile', 'industrialist', 'infant',
//   'influence', 'influential', 'inheritor', 'initiator', 'innocent', 'innovator', 'inspiration', 'inspirer',
//   'inspiriter', 'institutor', 'intellect', 'intellectual', 'intelligentsia', 'intimate', 'introducer', 'inventor',
//   'invitee', 'inviter', 'iranophile', 'jazzophile', 'jewel', 'keeper', 'key', 'kingpin', 'knight', 'knockout',
//   'ladies+man', 'lady', 'lamb', 'latinophile', 'latitudinarian', 'laureate', 'lead', 'leader', 'leading+figure',
//   'leading+light', 'legatee', 'legator', 'legend', 'legislator', 'liberal', 'libertarian', 'librocubicularist',
//   'lieutenant', 'life+of+the+party', 'lightworker', 'linguaphile', 'little+one', 'livewire', 'live+one', 'logophile',
//   'lollapalozza', 'lord', 'lover', 'lulu', 'luminary', 'maestro', 'magician', 'magistrate', 'maker', 'major+domo',
//   'manager', 'marquess', 'marquis', 'marvel', 'master', 'mastermind', 'matriarch', 'materfamilias', 'maven', 'mediator',
//   'meditator', 'meliorist', 'memory+maker', 'mentor', 'metropolitan', 'minder', 'miracle', 'miracle+worker',
//   'mitigator', 'mate', 'model', 'mom', 'monitor', 'moppet', 'mother', 'motor', 'mover', 'mover+and+shaker', 'motivator',
//   'musicophile', 'mycophile', 'nabob', 'neighbour', 'nemophilist', 'neophile', 'neonate', 'neoteric', 'nestling',
//   'newborn', 'nipper', 'nobleman', 'nonesuch', 'notable', 'no+slouch', 'number+one', 'numero+uno', 'nurse', 'nursling',
//   'nurturer', 'object+of+affection', 'officer', 'official', 'offspring', 'oenophile', 'omnist', 'one+and+only',
//   'operator', 'optimist', 'orchestrator', 'orchidophile', 'organizer', 'original', 'originator', 'ornithophile',
//   'overseer', 'owner', 'pacifier', 'pal', 'paladin', 'pangloss', 'pansophist', 'paraclete', 'paradigm', 'paragon',
//   'paramount', 'pard', 'parent', 'participant', 'partisan', 'partner', 'paterfamilias', 'pathfinder', 'patriarch',
//   'patron', 'peach', 'pearl', 'peacekeeper', 'peacemaker', 'peer', 'percipient', 'perfectibilian', 'perfectibilist',
//   'perfectionist', 'performer', 'personality', 'persophile', 'pet', 'phenom', 'phenomenon', 'philalethist',
//   'philanthropist', 'philomath', 'philogynist', 'philonoist', 'philosopher', 'pigsney', 'pilot', 'pioneer', 'pip',
//   'pippin', 'pinnacle', 'pinup', 'pin+up', 'pistol', 'planner', 'player', 'playmate', 'plum', 'pluviophile', 'poet',
//   'policy+maker', 'polymath', 'pogonophile', 'possessor', 'postulant', 'potentate', 'power+broker', 'powerhouse',
//   'preceptor', 'premier', 'presence', 'presenter', 'president', 'prevailer', 'prime+mover', 'primogenitor', 'prince',
//   'princess', 'principal', 'pro', 'problem+solver', 'proconsul', 'procreator', 'proctor', 'prodigy', 'producer',
//   'professional', 'professor', 'progeny', 'progenitor', 'promoter', 'promulgator', 'prophet', 'propitiator',
//   'proponent', 'proposer', 'proprietor', 'protagonist', 'protean', 'protector', 'protege', 'protegee', 'provider',
//   'publisher', 'purist', 'purveyor', 'qualtagh', 'raconteur', 'raconteuse', 'rain+maker', 'reacher', 'receiver',
//   'recipient', 'reliever', 'regulator', 'rejoicer', 'representative', 'researcher', 'resolver', 'resource',
//   'retrophile', 'rewarder', 'right+hand+person', 'ripsnorter', 'role+model', 'romantic', 'romeo', 'rooter', 'ruler',
//   'runner', 'russophile', 'sage', 'saint', 'salt+of+the+earth', 'santa+claus', 'saver', 'saviour', 'savant', 'schatzi',
//   'scholar', 'scholarch', 'scion', 'scripter', 'sculptor', 'secret+weapon', 'seeker', 'self+starter', 'sentinel',
//   'servant', 'server', 'sharpy', 'shaver', 'significant+other', 'sinophile', 'sire', 'sister', 'skipper', 'small+fry',
//   'smoothie', 'soul', 'soul+mate', 'sovereign', 'spark+plug', 'specialist', 'sponsor', 'sprite', 'sprout', 'squire',
//   'standard', 'standout', 'star', 'straight+shooter', 'stipendiary', 'strategist', 'socializer', 'socius',
//   'sockdolager', 'sockdologer', 'solon', 'something', 'something+else', 'specialist', 'stabilizer', 'staker',
//   'steward', 'stipendiary', 'stripling', 'striver', 'student', 'stylist', 'success', 'successor', 'sugar', 'suitor',
//   'superintendent', 'superior', 'superman', 'superstar', 'superwoman', 'supervisor', 'supplier', 'support',
//   'supporter', 'surety', 'survivor', 'swain', 'sweetheart', 'tadpole', 'teacher', 'teammate', 'a+10', 'technophile',
//   'testator', 'teutonophile', 'teutophile', 'thalassophile', 'thaumatologist', 'theodidact', 'theotokos', 'thinker',
//   'titleholder', 'tootsie', 'top+dog', 'tot', 'trailblazer', 'trainer', 'treasure', 'trier', 'true+love', 'trustee',
//   'turophile', 'tutelary', 'tutor', 'tycoon', 'typhlophile', 'underwriter', 'up+and+comer', 'upholder', 'urchin',
//   'validator', 'valedictorian', 'vaulter', 'victor', 'victress', 'victrix', 'videophile', 'viscount', 'vip', 'visitor',
//   'visionary', 'virtuoso', 'volunteer', 'votary', 'warantee', 'warantor', 'warden', 'wellspring', 'well+wisher',
//   'wheeler+and+dealer', 'whip', 'whippersnapper', 'whiz', 'whiz+kid', 'whizz', 'wife', 'winner', 'wizard', 'wonder',
//   'wooer', 'wordsmith', 'workhorse', 'workmate', 'worshiper', 'writer', 'wunderkind', 'youngster', 'younker', 'youth',
//   'xenophile'];
